# Generated by Django 2.1.1 on 2018-09-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QQ', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authmodel',
            options={'verbose_name': 'QQ登录用户数据', 'verbose_name_plural': 'QQ登录用户数据'},
        ),
        migrations.AlterModelTable(
            name='authmodel',
            table='st_qq',
        ),
    ]
